//
//  ViewControllerProtocol.h
//  STCBinder
//
//  Created by chenxiancai on 2019/10/7.
//  Copyright © 2019 stevchen. All rights reserved.
//

#ifndef ViewControllerProtocol_h
#define ViewControllerProtocol_h
#import <objc/runtime.h>

typedef unsigned char u_char;
typedef unsigned short u_short;
typedef unsigned int u_int;
typedef unsigned long u_long;
typedef long long long_long;
typedef unsigned long long u_long_long;
typedef void * point;
typedef char * c_point;

#define TEST_METHOD_WITH_TYPE_AND_ARG(type)\
- (type)type##MethodWithParam1:(type)param1 andParam2:(type)param2;

#define TEST_METHOD_WITH_TYPE_WITHOUT_ARG(type)\
- (type)type##Method;


@protocol viewControllerProtocol <NSObject>

TEST_METHOD_WITH_TYPE_WITHOUT_ARG(BOOL)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(char)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(u_char)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(short)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(u_short)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(int)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(u_int)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(long)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(u_long)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(long_long)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(u_long_long)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(float)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(double)

TEST_METHOD_WITH_TYPE_WITHOUT_ARG(Class)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(SEL)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(c_point)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(point)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(CGSize)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(CGPoint)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(CGVector)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(CGRect)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(CGAffineTransform)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(UIEdgeInsets)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(UIOffset)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(NSDirectionalEdgeInsets)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(NSRange)
TEST_METHOD_WITH_TYPE_WITHOUT_ARG(CATransform3D)

TEST_METHOD_WITH_TYPE_AND_ARG(BOOL)
TEST_METHOD_WITH_TYPE_AND_ARG(char)
TEST_METHOD_WITH_TYPE_AND_ARG(u_char)
TEST_METHOD_WITH_TYPE_AND_ARG(short)
TEST_METHOD_WITH_TYPE_AND_ARG(u_short)
TEST_METHOD_WITH_TYPE_AND_ARG(int)
TEST_METHOD_WITH_TYPE_AND_ARG(u_int)
TEST_METHOD_WITH_TYPE_AND_ARG(long)
TEST_METHOD_WITH_TYPE_AND_ARG(u_long)
TEST_METHOD_WITH_TYPE_AND_ARG(long_long)
TEST_METHOD_WITH_TYPE_AND_ARG(u_long_long)
TEST_METHOD_WITH_TYPE_AND_ARG(float)
TEST_METHOD_WITH_TYPE_AND_ARG(double)

TEST_METHOD_WITH_TYPE_AND_ARG(Class)
TEST_METHOD_WITH_TYPE_AND_ARG(SEL)
TEST_METHOD_WITH_TYPE_AND_ARG(c_point)
TEST_METHOD_WITH_TYPE_AND_ARG(point)
TEST_METHOD_WITH_TYPE_AND_ARG(CGSize)
TEST_METHOD_WITH_TYPE_AND_ARG(CGPoint)
TEST_METHOD_WITH_TYPE_AND_ARG(CGVector)
TEST_METHOD_WITH_TYPE_AND_ARG(CGRect)
TEST_METHOD_WITH_TYPE_AND_ARG(CGAffineTransform)
TEST_METHOD_WITH_TYPE_AND_ARG(UIEdgeInsets)
TEST_METHOD_WITH_TYPE_AND_ARG(UIOffset)
TEST_METHOD_WITH_TYPE_AND_ARG(NSDirectionalEdgeInsets)
TEST_METHOD_WITH_TYPE_AND_ARG(NSRange)
TEST_METHOD_WITH_TYPE_AND_ARG(CATransform3D)

@end

#endif /* ViewControllerProtocol_h */

